[[main]]
  name = "News"
  url = "/news/"
  weight = 10

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henkverlinde/"
  weight = 10

[[social]]
  name = "Twitter"
  url = "https://twitter.com/henkverlinde"
  weight = 20
