title = "Hyas"
titleSeparator = "-"
titleAddition = "The Smart, Flexible Hugo Starter"
description = "Hyas is The Smart, Flexible Hugo Starter. Create a site in minutes that is performant, accessible, and optimized for search engine results ranking."
images = ["social-fallback-image.jpg"]
twitterSite = "@henkverlinde"
twitterCreator = "@henkverlinde"
ogLocale = "en_US"
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaSection = "news"
siteLinksSearchBox = false

themeColor = "#fff"

# googleAnalytics = "UA-99999999-1"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 700, 500]
portraitPhotoWidths = [1500, 1000, 750]
lqipWidth = "20x"

footer = "Copyright © 2019 Henk Verlinde - MIT License"
