title = "Hyas"
titleSeparator = "-"
titleAddition = "Hugo starter helping you build fast, modern websites"
description = "Hyas is a Hugo starter with an easy development workflow helping you build fast, modern websites."
images = ["social-fallback-image.jpg"]
twitterSite = "@henkverlinde"
twitterCreator = "@henkverlinde"
ogLocale = "en_US"
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaSection = "news"
siteLinksSearchBox = false

themeColor = "#fff"

# googleAnalytics = "UA-99999999-1"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 700, 500]
portraitPhotoWidths = [1500, 1000, 750]
lqipWidth = "20x"

footer = "Copyright © 2019 Henk Verlinde - MIT License"

google_fonts = [
  ["Merriweather", "700"]
]

embed_google_fonts = false

# heading_font = "Merriweather"
# body_font = "Arial"
